### PR TITLE
Multiple selectors (Fixed #13)

### LINKED ISSUE #13: Prefix fails with second selector in multiple selectors
For example:

```
.my_class_1, .my_class_2 {...}
```

Result:

```
.no-svg .my_class_1, .my_class_2 {...}
```

So the second selector doesn't have no-svg class in it.

### PR DESCRIPTION
**Pull request by Kreozot**
Fixed #13. Now fallbackSelector adds to each selector in multiple selectors statement.

### CODE REVIEW

**Comment by justim** [comment]
Awesome, thanks!

**Comment by Kreozot** [comment]
You're welcome! But why are you don't merging PRs and create your own branches and merge them instead?

**Comment by justim** [comment]
Because I'm basically merging your branch/commits, I just make a slight change to them, no need to create my own. Or am I missing something here?

**Comment by Kreozot** [comment]
Sorry, it was my misunderstanding :)

**Pull request closed without merging**
